<a href="https://colab.research.google.com/github/AnikaCeamin22/PyTorch/blob/main/Day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello I am excited to learn PyTorch")

Hello I am excited to learn PyTorch


In [2]:
# how i can access to a GPU
! nvidia-smi

Wed May 28 09:25:37 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


## Introduction to Tensors

### Creating Tensors

Pytorch tensors are created using `torch.Tensor` = https://docs.pytorch.org/docs/stable/tensors.html

In [4]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
# Number of dimention
scalar.ndim

0

In [6]:
# Get tensor back as Pyton int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([9,9])
vector

tensor([9, 9])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# Matrix
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[1,3,6]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [1, 3, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 4, 3])

### Random Tensors

Why random tensors?
Random Tensrs are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers->look at data->update random numbers->look at data->updata random numbers

Torch random tensor - https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [16]:
# create a random tensor of size(3,4)
random_tensor = torch.rand(22,9,1)
random_tensor

tensor([[[0.2729],
         [0.7203],
         [0.8026],
         [0.4367],
         [0.7195],
         [0.5523],
         [0.5440],
         [0.2759],
         [0.4271]],

        [[0.7303],
         [0.3377],
         [0.0844],
         [0.0062],
         [0.5325],
         [0.9807],
         [0.1491],
         [0.8140],
         [0.4449]],

        [[0.1485],
         [0.0620],
         [0.3135],
         [0.0088],
         [0.5854],
         [0.1034],
         [0.5673],
         [0.2983],
         [0.1199]],

        [[0.6663],
         [0.7273],
         [0.7256],
         [0.2520],
         [0.2013],
         [0.9974],
         [0.4955],
         [0.3939],
         [0.1438]],

        [[0.9972],
         [0.9735],
         [0.8664],
         [0.4151],
         [0.8563],
         [0.8916],
         [0.3500],
         [0.4493],
         [0.5370]],

        [[0.8835],
         [0.5299],
         [0.1437],
         [0.4196],
         [0.2624],
         [0.4695],
         [0.9749],
  

In [17]:
random_tensor.ndim

3

In [18]:
random_tensor.shape

torch.Size([22, 9, 1])

In [19]:
# Create a random tensor with similar shapes to an image tensor
random_image_size_tensor = torch.rand(size=(3,22,9)) # colour channels(R,G,B),hight, width
random_image_size_tensor;

In [20]:
random_image_size_tensor.ndim

3

In [21]:
random_image_size_tensor.shape

torch.Size([3, 22, 9])

### Create zeros and ones

In [22]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(22,9))
zeros

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0

In [23]:
# Create a tensor of all ones
ones = torch.ones(size=(22,9));
ones

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1

In [24]:
# torch default data type float32
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [25]:
# Use torch.range()
torch.range(9,22+1)

<ipython-input-25-a8845703d5ea>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(9,22+1)


tensor([ 9., 10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
        23.])

In [28]:
# Use torch.range() and get deprecated message, use torch.arange()
torch.arange(start = 9, end = 22+1, step = 1.5)

tensor([ 9.0000, 10.5000, 12.0000, 13.5000, 15.0000, 16.5000, 18.0000, 19.5000,
        21.0000, 22.5000])

In [29]:
# Creating tensors like
one_to_ten = torch.arange(1,10)
ten_zeros = torch.zeros_like(input = one_to_ten);
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])